name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  built:
    runs-on: ubuntu-latest

    steps:
      - name: Проверить код из репозитория
        uses: actions/checkout@v2

      - name: Настройка проекта
        run: |
          make setup

      - name: Запуск тестов
        run: |
          make test

      - name: Запуск линтера
        run: |
          make lint
